USE ROLE ACCOUNTADMIN

-- Compute: extra-small, auto-suspend fast so that the trial credits last
CREATE WAREHOUSE IF NOT EXISTS ZOMATO_WH
    WAREHOUSE_SIZE  = 'XSMALL'
    AUTO_SUSPEND    = 60
    AUTO_RESUME     = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Database + Medallion Schemas
CREATE DATABASE IF NOT EXISTS ZOMATO;
CREATE SCHEMA IF NOT EXISTS ZOMATO.BRONZE;      -- Iceberg tables spark wrote (dbt sources)
CREATE SCHEMA IF NOT EXISTS ZOMATO.RAW;         -- Only used by the COPY fallback path
CREATE SCHEMA IF NOT EXISTS ZOMATO.STAGING;     -- cleaned / conformed(dbt)
CREATE SCHEMA IF NOT EXISTS ZOMATO.MARTS;       -- Gold, Iceberg (dbt)
CREATE SCHEMA IF NOT EXISTS ZOMATO.SNAPSHOTS;   -- SCD2 history(dbt)
CREATE SCHEMA IF NOT EXISTS ZOMATO.AI;           -- LLM-enriched tables (OPENAI jobs)

-- A role dbt/Airflow will use.
CREATE ROLE     IF NOT EXISTS DBT_ROLE;
GRANT  USAGE    ON WAREHOUSE  ZOMATO_WH TO ROLE DBT_ROLE;
GRANT  OPERATE  ON WAREHOUSE  ZOMATO_WH TO ROLE DBT_ROLE;
GRANT  ALL      ON DATABASE   ZOMATO TO ROLE DBT_ROLE;
GRANT  ALL      ON ALL SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT  ALL      ON FUTURE SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT  ALL      ON FUTURE TABLES IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT  ALL      ON FUTURE VIEWS IN DATABASE ZOMATO TO ROLE DBT_ROLE;

-- login details to use the roles

SET my_user = CURRENT_USER();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($my_user);

SELECT 'setup complete' AS status;
